#!/usr/bin/env python3
"""Regenerate IconsFontAwesome6_Catalog.inl from IconsFontAwesome6.h.

Parses every `#define ICON_FA_<NAME> "<glyph>"` line and emits a
`{ "slug", ICON_FA_<NAME> }` aggregate-init row (one per icon) that
SmatchetIconPickerUi.cpp #includes into its catalog table. The glyph stays
the header macro (not a copied literal) so the catalog can never drift from
the font header. Re-run on a Font-Awesome header upgrade. Stdlib-only.
"""
import pathlib
import re

FA_DIR = pathlib.Path(__file__).resolve().parents[2] / "Source" / "Core" / "ThirdParty" / "IconsFontAwesome6"
HEADER = FA_DIR / "IconsFontAwesome6.h"
OUT = FA_DIR / "IconsFontAwesome6_Catalog.inl"
DEFINE = re.compile(r'^#define\s+(ICON_FA_\w+)\s+"')

rows = []
for line in HEADER.read_text(encoding="utf-8").splitlines():
    m = DEFINE.match(line)
    if m:
        macro = m.group(1)
        slug = macro[len("ICON_FA_"):].lower().replace("_", "-")
        rows.append('    {{"{0}", {1}}},'.format(slug, macro))

banner = "// Generated by scripts/dev/gen-fa-catalog.py from IconsFontAwesome6.h. Do not edit.\n"
OUT.write_text(banner + "\n".join(rows) + "\n", encoding="utf-8")
print("gen-fa-catalog: wrote {0} icons -> {1}".format(len(rows), OUT))
