# scripts/dev/merge-watcher-install-autostart.ps1
# ----------------------------------------------------------------------------
# Register a Windows Scheduled Task that starts `merge-watcher.py daemon` at
# user login. Phase 4c of `docs/design/smatchet-merge-watcher.md`.
#
# Idempotent -- re-running unregisters + re-registers, so updates to the
# arguments (e.g. switching poll interval) take effect on next run.
#
# Limited run-level (no UAC prompt; daemon runs as current user). Restart on
# crash: up to 3 times, 5 min apart. Log file:
#   %LOCALAPPDATA%\Smatchet\merge-watch\daemon.log
#
# Usage:
#   powershell -ExecutionPolicy Bypass -File scripts/dev/merge-watcher-install-autostart.ps1
#
# Optional parameters:
#   -PollInterval <seconds>  Override MERGE_WATCH_POLL_INTERVAL (default 60).
#   -PythonExe <path>        Override the Python interpreter. Defaults to
#                            the `python` resolved on PATH at install time.
#   -TaskName <name>         Override "SmatchetMergeWatcher".
# ----------------------------------------------------------------------------

param(
    [int]$PollInterval = 60,
    [string]$PythonExe = "",
    [string]$TaskName = "SmatchetMergeWatcher"
)

$ErrorActionPreference = "Stop"

# Resolve repo root from script location (this file lives at
# <repo>/scripts/dev/merge-watcher-install-autostart.ps1).
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = Split-Path -Parent (Split-Path -Parent $scriptDir)
$daemonScript = Join-Path $scriptDir "merge-watcher.py"

if (-not (Test-Path $daemonScript)) {
    Write-Error "merge-watcher.py not found at expected path: $daemonScript"
    exit 1
}

# Resolve Python -- explicit param wins, else first `python` on PATH.
if ([string]::IsNullOrEmpty($PythonExe)) {
    $pythonCmd = Get-Command python -ErrorAction SilentlyContinue
    if (-not $pythonCmd) {
        Write-Error "No 'python' on PATH. Install Python 3 or pass -PythonExe <path>."
        exit 1
    }
    $PythonExe = $pythonCmd.Source
}
if (-not (Test-Path $PythonExe)) {
    Write-Error "Python interpreter not found at: $PythonExe"
    exit 1
}

# Resolve log dir (matches the daemon's `watcher_root()` resolution).
$logDir = Join-Path $env:LOCALAPPDATA "Smatchet\merge-watch"
if (-not (Test-Path $logDir)) {
    New-Item -ItemType Directory -Path $logDir -Force | Out-Null
}
$logFile = Join-Path $logDir "daemon.log"

# Resolve gh + bash locations at install time. The scheduled task inherits a
# minimal PATH (system PATH, NOT the interactive user's PATH), so without
# explicit augmentation `merge-gates.sh` exits 127 (command not found) every
# poll inside the daemon. Bake the dirs holding gh.exe + bash.exe into the
# task command so the daemon's bash subprocess can resolve them.
$ghCmd = Get-Command gh -ErrorAction SilentlyContinue
if (-not $ghCmd) {
    Write-Error "No 'gh' on PATH. Install GitHub CLI (https://cli.github.com/) -- merge-gates.sh relies on it."
    exit 1
}
$bashCmd = Get-Command bash -ErrorAction SilentlyContinue
if (-not $bashCmd) {
    Write-Error "No 'bash' on PATH. Install Git for Windows (provides bash.exe) -- merge-gates.sh runs under bash."
    exit 1
}
$ghDir = Split-Path -Parent $ghCmd.Source
$bashDir = Split-Path -Parent $bashCmd.Source
$pathAugment = "$ghDir;$bashDir"

# Resolve ORCH_USER once at install time via 'gh api user --jq .login'. This
# value identifies "self" in the merge-gates user-comments check so a CR
# review from yourself doesn't block your own merge. Without ORCH_USER set,
# merge-gates.sh aborts immediately and the watcher records EXIT_127 every poll.
$orchUser = (& $ghCmd.Source api user --jq .login 2>$null)
if ([string]::IsNullOrEmpty($orchUser)) {
    Write-Error "Failed to resolve ORCH_USER via 'gh api user --jq .login'. Run 'gh auth login' first."
    exit 1
}
Write-Host "Resolved env for daemon:"
Write-Host "  gh.exe:    $($ghCmd.Source)"
Write-Host "  bash.exe:  $($bashCmd.Source)"
Write-Host "  ORCH_USER: $orchUser"

# Unregister any existing task with this name to keep install idempotent.
$existing = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
if ($existing) {
    Write-Host "Unregistering existing '$TaskName' before re-installing..."
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
}

# Write a wrapper .bat next to the log file so Task Scheduler can launch a
# clean Execute+Argument pair without nested-quote surprises. Cramming
# `set PATH=… && set ORCH_USER=… && python …` directly into a `cmd /c "…"`
# argument got mangled by Task Scheduler's parser (LastTaskResult=1 with
# no log output), because the quoted-`set` form (`set "K=V"`) and the
# `"python.exe"` wrapper double-quotes both want to be the OUTER quotes
# of the cmd.exe argument string. Punting to a real .bat is the standard
# Windows fix and keeps the install script readable.
$wrapperBat = Join-Path $logDir "run-merge-watcher.bat"
$wrapperLines = @(
    "@echo off",
    "REM Auto-generated by merge-watcher-install-autostart.ps1 -- do not edit; re-run the installer.",
    "set ""PATH=$pathAugment;%PATH%""",
    "set ""ORCH_USER=$orchUser""",
    "REM Python under cmd.exe defaults to cp1252 for stdout. merge-watcher prints arrows",
    "REM (U+2192) and other non-ASCII glyphs in its poll lines; without UTF-8 stdout the",
    "REM daemon crashes on the first interesting log line and Task Scheduler shows",
    "REM LastTaskResult=1 with a partial daemon.log.",
    "set ""PYTHONIOENCODING=utf-8""",
    "REM `-u` disables stdout/stderr buffering so daemon.log gets per-poll lines",
    "REM as they happen instead of only at process exit.",
    "`"$PythonExe`" -u `"$daemonScript`" daemon --poll-interval $PollInterval > `"$logFile`" 2>&1"
)
$wrapperLines | Out-File -FilePath $wrapperBat -Encoding ASCII -Force
Write-Host "  Wrapper:   $wrapperBat"

$action = New-ScheduledTaskAction `
    -Execute "cmd.exe" `
    -Argument "/c `"$wrapperBat`"" `
    -WorkingDirectory $repoRoot

# Trigger: at login of the user running this install. The task runs in this
# user's identity (RunLevel Limited = no admin token).
$trigger = New-ScheduledTaskTrigger -AtLogOn -User $env:USERNAME

# Restart-on-crash: up to 3 attempts, 5 min apart.
# ExecutionTimeLimit of TimeSpan::Zero = no time limit (daemon runs indefinitely).
$settings = New-ScheduledTaskSettingsSet `
    -StartWhenAvailable `
    -RestartCount 3 `
    -RestartInterval (New-TimeSpan -Minutes 5) `
    -ExecutionTimeLimit ([TimeSpan]::Zero) `
    -MultipleInstances IgnoreNew

Register-ScheduledTask `
    -TaskName $TaskName `
    -Action $action `
    -Trigger $trigger `
    -Settings $settings `
    -RunLevel Limited `
    -Description "Smatchet merge-watcher daemon -- polls registered PRs + auto-merges per docs/design/smatchet-merge-watcher.md" | Out-Null

Write-Host ""
Write-Host "[OK] Scheduled Task '$TaskName' registered." -ForegroundColor Green
Write-Host "  Repo:           $repoRoot"
Write-Host "  Daemon script:  $daemonScript"
Write-Host "  Python:         $PythonExe"
Write-Host "  Poll interval:  $PollInterval seconds"
Write-Host "  Log file:       $logFile"
Write-Host ""
Write-Host "Daemon will start on next login. Start now with:"
Write-Host "  Start-ScheduledTask -TaskName $TaskName"
Write-Host ""
Write-Host "Check / control:"
Write-Host "  Get-ScheduledTask -TaskName $TaskName"
Write-Host "  Stop-ScheduledTask -TaskName $TaskName"
Write-Host "  Get-Content $logFile -Tail 20"
Write-Host ""
Write-Host "Uninstall:"
Write-Host "  powershell -ExecutionPolicy Bypass -File $scriptDir\merge-watcher-uninstall-autostart.ps1"
