#!/usr/bin/env bash
# scripts/dev/perf-marker-inventory.sh — emit a markdown inventory of all
# checked-in SMATCHET_UI_PERF_SCOPE markers, grouped by subsystem +
# separated from in-flight `perf_temp:*` markers.
#
# Slice 4 of docs/plans/shipped/pillar-1-2-perf-review-system.md. Auto-enrolled via
# scripts/dev/test-all.sh as an ADVISORY check — emits a one-line WARN if the
# regenerated docs/perf/MARKER_INVENTORY.md differs from the checked-in
# version. Does NOT fail the test pass; the rebuild is a doc hygiene signal.
#
# Usage:
#   bash scripts/dev/perf-marker-inventory.sh                # regenerate doc
#   bash scripts/dev/perf-marker-inventory.sh --check        # compare only

set -uo pipefail

# REPO_ROOT (the tree to scan) is overridable via SMATCHET_MARKER_REPO_ROOT so the
# leak-gate test can regenerate the inventory over a throwaway fixture tree (#329).
REPO_ROOT="${SMATCHET_MARKER_REPO_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
# Hard-fail on cd: this script WRITES docs/perf/MARKER_INVENTORY.md as a
# repo-relative path. A failed cd would land the write wherever the
# caller happened to be cwd'd in — bug, not a no-op.
cd "$REPO_ROOT" || { echo "ERROR: cd to $REPO_ROOT failed" >&2; exit 1; }

CHECK_ONLY=0
case "${1:-}" in
    --check) CHECK_ONLY=1 ;;
esac

# OUT_FILE is overridable via MARKER_INVENTORY_OUT so a caller can regenerate the
# inventory to a throwaway path without clobbering the committed doc (#329 leak gate).
OUT_FILE="${MARKER_INVENTORY_OUT:-docs/perf/MARKER_INVENTORY.md}"
TMP_FILE="$(mktemp -t marker-inventory-XXXXXX.md)"

# Collect every SMATCHET_UI_PERF_SCOPE invocation across first-party trees.
# Skip vendored ThirdParty.
declare -a markers_committed=()
declare -a markers_temp=()

while IFS= read -r line; do
    [[ -z "$line" ]] && continue
    file="${line%%:*}"
    rest="${line#*:}"
    line_num="${rest%%:*}"
    text="${rest#*:}"
    # Extract the string literal between the first ( " and the next " ).
    name="$(printf '%s' "$text" | sed -n 's/.*SMATCHET_UI_PERF_SCOPE([^"]*"\([^"]*\)".*/\1/p')"
    [[ -z "$name" ]] && continue
    if [[ "$name" == perf_temp:* ]]; then
        markers_temp+=("$file:$line_num	$name")
    else
        markers_committed+=("$file:$line_num	$name")
    fi
done < <(
    grep -rnE 'SMATCHET_UI_PERF_SCOPE\([[:space:]]*"' \
        Source/Core/include Source/Core/src Plugins Source/Standalone tests 2>/dev/null \
        | grep -v "ThirdParty/" \
        | grep -v "^Binary file" \
        | grep -v -- '--$' || true
)

# Sort + group by subsystem (first path component after Source/Core/src/ etc.).
subsystem_of() {
    local p="$1"
    case "$p" in
        Source/Core/src/Commands/*)         echo "Source/Core / Commands" ;;
        Source/Core/src/Scenarios/*)        echo "Source/Core / Scenarios" ;;
        Source/Core/src/*Ui*.cpp)           echo "Source/Core / UI" ;;
        Source/Core/src/*Grid*.cpp|Source/Core/src/TicketGrid*.cpp) echo "Source/Core / Grid" ;;
        Source/Core/src/Ai*.cpp|Source/Core/src/SmatchetAi*.cpp) echo "Source/Core / AI" ;;
        Source/Core/src/Tracker*.cpp|Source/Core/src/JiraClient*.cpp) echo "Source/Core / Tracker" ;;
        Source/Core/src/*.cpp)              echo "Source/Core / other" ;;
        Source/Core/include/*)              echo "Source/Core / headers" ;;
        Source/Plugins/Mcp/*)                      echo "Plugins / MCP" ;;
        Source/Plugins/LuaConsole/*)               echo "Plugins / Lua" ;;
        Source/Plugins/Whisper/*)                  echo "Plugins / Whisper" ;;
        Source/Standalone/*)                echo "Source/Standalone" ;;
        tests/*)                            echo "tests" ;;
        *)                                  echo "other" ;;
    esac
}

{
    echo "# Smatchet perf-marker inventory"
    echo ""
    echo "> Auto-generated by \`scripts/dev/perf-marker-inventory.sh\`. **Do not hand-edit.**"
    echo "> Inventory of every \`SMATCHET_UI_PERF_SCOPE(...)\` macro invocation across"
    echo "> first-party trees (\`Source/Core\`, \`Plugins\`, \`Source/Standalone\`, \`tests\`),"
    echo "> vendored \`ThirdParty/\` excluded. Slice 4 of"
    echo "> \`docs/plans/shipped/pillar-1-2-perf-review-system.md\`."
    echo ""
    echo "Last regenerated at: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo ""
    echo "## Committed markers"
    echo ""
    echo "Production scopes that ship in every build. Names are stable contract surface — \`perf.snapshot\` keys, baseline rows, agent reports."
    echo ""
    if [[ ${#markers_committed[@]} -eq 0 ]]; then
        echo "(none)"
        echo ""
    else
        # bash associative arrays + `set -u` don't play well with read-of-
        # missing-key; iterate via a sorted unique-subsystem list instead.
        declare -a subs_seen=()
        declare -A seen_set=()
        for entry in "${markers_committed[@]}"; do
            file="${entry%%:*}"
            sub="$(subsystem_of "$file")"
            if [[ -z "${seen_set[$sub]:-}" ]]; then
                subs_seen+=("$sub")
                seen_set[$sub]=1
            fi
        done
        # Sort the unique subsystem list (newline-quoted to preserve spaces).
        IFS=$'\n' subs_sorted=($(printf '%s\n' "${subs_seen[@]}" | sort -u))
        unset IFS
        for sub in "${subs_sorted[@]}"; do
            echo "### $sub"
            echo ""
            echo "| location | scope name |"
            echo "|---|---|"
            # Pull all entries matching this sub, sorted by file:line.
            for entry in "${markers_committed[@]}"; do
                file="${entry%%:*}"
                this_sub="$(subsystem_of "$file")"
                [[ "$this_sub" != "$sub" ]] && continue
                # entry is "file:line<TAB>name".
                loc="${entry%	*}"
                name="${entry#*	}"
                echo "| \`$loc\` | \`$name\` |"
            done | sort
            echo ""
        done
    fi
    echo "## In-flight \`perf_temp:*\` markers"
    echo ""
    echo "Temporary markers added by \`perf-instrument\` / \`perf-detective\` / \`spike-hunter\` for an active investigation. **These must NEVER ship to develop** — the strip step is part of every perf-investigation closing protocol."
    echo ""
    if [[ ${#markers_temp[@]} -eq 0 ]]; then
        echo "(none — clean tree)"
        echo ""
    else
        echo "| location | scope name |"
        echo "|---|---|"
        printf '%s\n' "${markers_temp[@]}" | sort | while IFS=$'\t' read -r loc name; do
            [[ -z "$loc" ]] && continue
            echo "| \`$loc\` | \`$name\` |"
        done
        echo ""
        echo "**WARN — $((${#markers_temp[@]})) in-flight \`perf_temp:*\` marker(s) detected. Strip before merging.**"
        echo ""
    fi
} > "$TMP_FILE"

if [[ $CHECK_ONLY -eq 1 ]]; then
    # Strip the volatile timestamp line before diffing — the doc rewrites it
    # on every regeneration, so a literal diff would always WARN.
    norm_existing="$(mktemp -t mki-existing-XXXXXX.md)"
    norm_fresh="$(mktemp -t mki-fresh-XXXXXX.md)"
    [[ -f "$OUT_FILE" ]] && grep -v '^Last regenerated at:' "$OUT_FILE" > "$norm_existing" || true
    grep -v '^Last regenerated at:' "$TMP_FILE" > "$norm_fresh"
    if [[ -f "$OUT_FILE" ]] && diff -q "$norm_existing" "$norm_fresh" > /dev/null 2>&1; then
        echo "[marker-inventory] $OUT_FILE up-to-date."
        rm -f "$TMP_FILE" "$norm_existing" "$norm_fresh"
        exit 0
    fi
    echo "WARN: $OUT_FILE differs from regenerated content. Run 'bash scripts/dev/perf-marker-inventory.sh' to refresh." >&2
    rm -f "$TMP_FILE" "$norm_existing" "$norm_fresh"
    exit 0  # advisory — does not fail
fi

mkdir -p "$(dirname "$OUT_FILE")"
mv "$TMP_FILE" "$OUT_FILE"
echo "[marker-inventory] wrote $OUT_FILE (${#markers_committed[@]} committed, ${#markers_temp[@]} perf_temp:*)."
